openapi: 3.0.0
info:
  title: Differ Template API
  version: 1.0.0
paths:
  /:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string 